### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Tribex** [wanadev/PhotonUI#5] opened 2015-03-15 23:29 UTC
I'd like to know if this repository is still actively developed. I love the work you've done so far and it looks amazing and well done.

I've made some serious changes over on my [fork](https://github.com/Fourth-Corner-Software/PhotonUI/commit/a387484fe96c6e0f87f1c9459141ffa18683e5b7), mainly related to modernizing and standardizing the build system, and it introduces significant incompatibilities between this repository and my own. Any changes to that fork will likely be incompatible with this one.

I'd simply like to know if it would be worth it to take the effort to maintain a separate branch which more closely mirrors to this one, so that any improvements can be contributed back to this repository.

Keep up the good work!
 -Tribex

**Comment by flozz** [comment] 2015-03-16 10:16
Hello,

PhotonUI is still developed (but currently, it is not actively developed). I think you've made a great work with your fork. I tested it on a project I have, there is some broken things but it is very easy to fix. I think we can consider to merge your work into our master branch (after fixing some few things), there is no reason to maintain two separated branches. :)

Regards,

**Comment by Tribex** [comment] 2015-03-16 11:24
@flozz Ah, I'm glad to hear that!
I'm aware of several issues in my fork, mainly related to CSS, which should hopefully be fixed when I refactor the CSS build system. (Convert it all to LESS with extensive @import statements. Perhaps flatten the theme a bit as well.)

What other issues did you notice? I haven't done much testing except on the demos and one of my programs.

I'd be more than happy to contribute to this repository as much as possible, what sort of guidelines do you have for doing so?

Here's a list of what I have sort of planned, by order of personal priority:
 * Rewrite stylesheets as LESS with extensive variables. Standardize the colors a bit.
 * Streamline the demo/doc build process, auto-generate the demo index.html.
 * Clean up and comment Gruntfile.js.
 * Move docs and demos into gh-pages branch.
 * Consider the feasibility of adding a CodeAreaField using Ace or CodeMirror.
 * Add something akin to tabs, perhaps through layouts or a compound widget.
 * Add some sort of Table widget.
 * Add some sort of TreeView widget.

Note that all of the above takes a backseat to a work project I'm developing, so I can't dedicate that much time to it.

How much do you guys use PhotonUI for? Any idea on how much it is used outside of your company? How important is API compatibility?

Thanks for responding,
 -Tribex

**Comment by flozz** [comment] 2015-03-16 14:14
Hello,


> What other issues did you notice? I haven't done much testing except on the demos and one of my programs.

* `demo/style.css`,  `demo/images/sprites.png`,  `demo/highlightjs/github.css` and  `demo/highlightjs/highlight.pack.js` are missing in the branch,
* I think the old `photonui.palette` should be "attached" do `photonui.ColorPalette` and not `photonui.Color`,
* there is a wrong behavior with Stone.js translation files, but it needs to be fixed in Stone.js itself (not a big deal),
* and I think we must be able to access to `Class` outside of the closure too (`photonui.Class`, `photonui.lib.Class` or something similar).


> what sort of guidelines do you have for doing so?

We mainly follow the [Airbnb conventions](https://github.com/airbnb/javascript) (except for few details, like 4 space indentation). There is currently no more guidelines.


> Note that all of the above takes a backseat to a work project I'm developing, so I can't dedicate that much time to it.

Same here: PhotonUI grows with the projects' needs.


> How much do you guys use PhotonUI for?

Currently, we have only few projects that use it (4).


> Any idea on how much it is used outside of your company?

No idea, but I don't think it is wildly used...


> How important is API compatibility?

Currently, the API is not considered as "stable", so it can change a little bit, there is no problem.


Best regards,

**Comment by Tribex** [comment] 2015-03-16 22:55
> demo/style.css, demo/images/sprites.png, demo/highlightjs/github.css and demo/highlightjs/highlight.pack.js are missing in the branch,

Oops, Not sure how that happened. Returning in next commit. :)

> I think the old photonui.palette should be "attached" do photonui.ColorPalette and not photonui.Color,

Hmm, I remember splitting it out for a reason related to a dependency loop, but I'll try and stick it back.

> and I think we must be able to access to Class outside of the closure too (photonui.Class, photonui.lib.Class or something similar).

Excellent idea. Perhaps all the lib classes. (Class, Stone, and KeyboardJS) should be accessible from a photonui.lib object?

> We mainly follow the Airbnb conventions (except for few details, like 4 space indentation). There is currently no more guidelines.

Alright, I'll try and switch it over to those then, shouldn't take too long.

Thank you,
-Tribex

**Comment by flozz** [comment] 2015-03-17 12:14
> Perhaps all the lib classes. (Class, Stone, and KeyboardJS) should be accessible from a photonui.lib object?

Yes, I think it is the best thing to do :)

We should be able to merge your work as soon as the *less* conversion is finished if there is no additional issue.

I also have to write a fix for Stone.js in order to fix a misbehavior (currently it expects to have a `window.Stone` object, I will avoid this, using an event to load translations).

**Comment by Tribex** [comment] 2015-03-17 13:38
Alright, dependencies are now under photonui.lib.

The LESS conversion will take quite a lot of time, as it will require a serious rewrite of all of the CSS.

I just removed the last reference to window.Stone in the latest commit, and as far as I can tell, nothing else expects it. What are you referring to exactly?

**Comment by flozz** [comment] 2015-03-17 13:45
> I just removed the last reference to window.Stone in the latest commit, and as far as I can tell, nothing else expects it. What are you referring to exactly? I'm using the CommonJS version from the latest Stone master.

When you build a Stone.js catalog as a single javascript file, it generates a js that looks like that:

```javascript
Stone.addCatalogs({
    "fr": {
        "About": "À propos", 
        "Background": "Arrière-plan", 
        "Cancel": "Annuler", 
        ...
    }
})
```
so you just have to include the script in the page and it work. I just have to change the way the generated js catalog is loaded.

**Comment by Tribex** [comment] 2015-03-17 14:03
Ah, okay. Didn't think of that.

**Comment by flozz** [comment] 2015-03-17 14:07
As I said, it's not a big deal, it is very easy to fix ;)

**Comment by Tribex** [comment] 2015-03-23 23:24
I apologize for the delay, after taking a look, my LESS skills were not quite up to par for a project of this magnitude, so I'm now working on a smaller project to get them up to speed. I'll probably start in earnest sometime later this week, or in two weeks.

**Comment by flozz** [comment] 2015-03-24 08:26
Ok, no problem. I have to work my LESS too ;)

**Comment by Tribex** [comment] 2015-03-28 10:39
Alright, initial structure for the layout of the Less files and the Grunt build steps is added, but I've largely run out of time this week to work on random projects. The actual conversion will probably have to wait until the week after next.

See ya then!

**Comment by flozz** [comment] 2015-03-30 07:57
Hello,

Sorry for the long time I take to answer. It is ok for me, I think a flat theme will look a way better than the actual theme.

:)

**Comment by Tribex** [comment] 2015-03-30 09:00
@flozz No problem, you don't need to feel obligated to finishing this issue or anything. I'll handle it all as I have time. :)

I hope the theme will look okay, I'm not exactly good at design. x]

**Comment by Tribex** [comment] 2015-04-06 14:15
@flozz Alright, the initial Particle theme has been committed, I'm not a designer though, so it still doesn't feel that great. 

Colors are easily changed using `variables.less` in the theme directory. 

The base CSS has all been converted to Less as well, in the same fashion as a theme.
FontAwesome has been updated to 4.3.0 (latest), kind of accidentally. :P 

All demos should be working properly now with little or no glitches compared to before, you can test at http://fourth-corner-software.github.io/PhotonUI/demo/

Feel free to express opinions!

**Comment by flozz** [comment] 2015-04-06 15:01
Hello,

I took a look on what you've done and it seems quite good. I'll look more in detail tomorrow, and I'll make some tests with your branch on various projects to be sure there is no major bug/regression before merging.

Thank you again for your great work :)

**Comment by Tribex** [comment] 2015-04-06 23:11
@flozz Alright, I'll be out of town for the next couple of days, but will resume working on it pretty soon. :)

**Comment by flozz** [comment] 2015-04-07 14:40
@Tribex After further testing, everything works well. The only remaining issue is the one with Stone.js. I updated the lib to fix that, you just have to update it in your branch :)

**Comment by Tribex** [comment] 2015-04-08 09:43
@flozz Excellent! I will update that as soon as I am free. Then I will squash the commits and remove docs and demos from the master branch and open a PR. 

Do you have any opinions on the theme?

Thank you for your time!

**Comment by flozz** [comment] 2015-04-08 13:47
@Tribex as you ask, I am not fan of the big black borders of the windows but this is not very important. The rest of the theme is ok :)

I also found a small bug with the selects when the text is too large. For example, try to select "Time New Roman" in this demo: http://fourth-corner-software.github.io/PhotonUI/demo/FontSelect.html

**Comment by flozz** [comment] 2015-04-08 13:50
Hum, maybe we should remove the "Lobster" and "Indie Flower" fonts on the FontSelect demo as they are Google Font that are no more imported in the demo.

**Comment by Tribex** [comment] 2015-04-08 23:30
@flozz Alright, I have removed the black borders and I have to agree with you that it looks better without them.
I'll work on the font select, I have a hunch that what caused it is similar to the issues I was having with menu.
I've removed the two fonts. Incidentally, Google fonts are inaccessible in my country anyways, so those fonts were displaying as normal serif for me. :3

**Closed** 2015-04-13 11:14 UTC
